# Generated by Django 5.2.4 on 2025-08-10 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpackage',
            name='duration_days',
            field=models.IntegerField(default=31, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(372)]),
            preserve_default=False,
        ),
    ]
