# Generated by Django 5.2.4 on 2025-08-07 00:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('register_date', models.DateField(unique=True)),
                ('is_opened', models.BooleanField(default=True)),
            ],
        ),
    ]
