# Generated by Django 5.2.4 on 2025-08-12 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_registers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
