# Generated by Django 5.2.4 on 2025-08-20 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_registers', '0002_cashregister_amount'),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='gym',
            field=models.ForeignKey(default='1de73766-3dac-4ad1-ba04-96b77b82099d', on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='gyms.gym'),
            preserve_default=False,
        ),
    ]
