# Generated by Django 5.2.4 on 2025-08-09 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_registers', '0001_initial'),
        ('payments', '0002_alter_payment_id_alter_payment_next_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cash_register',
            field=models.ForeignKey(default='28f02a5a-04aa-4dac-8198-522b1e618ecf', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cash_registers.cashregister'),
            preserve_default=False,
        ),
    ]
