# Generated by Django 5.2.4 on 2025-08-16 21:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvalue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
