# Generated by Django 5.2.4 on 2025-08-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentvalue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='observations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
