# Generated by Django 5.2.4 on 2025-08-28 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvalue',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_values', to='payments.payment'),
        ),
    ]
