# Generated by Django 5.2.4 on 2025-08-01 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gym_created_at_gym_updated_at'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gym',
            field=models.ForeignKey(default='9fd988e8-a685-4e61-972d-752214a9e9c6', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='gyms.gym'),
            preserve_default=False,
        ),
    ]
