# Generated by Django 5.2.4 on 2025-08-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_overdue',
            field=models.BooleanField(default=True),
        ),
    ]
