# Generated by Django 5.2.4 on 2025-08-23 02:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_overdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_overdue',
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_overdue', models.BooleanField(default=True)),
                ('last_checked', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='students.student', unique=True)),
            ],
        ),
    ]
