# Generated by Django 5.2.4 on 2025-08-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_is_overdue_studentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='students.student', unique=True),
        ),
    ]
